`ifndef DEFINE_STATE

// This defines the states

typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;


typedef enum logic [2:0] {
	S_IDLE,
	S_ENABLE_UART_RX,
	S_WAIT_UART_RX,
	S_M1,
	S_M2
} top_state_type;

typedef enum logic [1:0] {
	S_TXC_IDLE,
	S_TXC_START_BIT,
	S_TXC_DATA,
	S_TXC_STOP_BIT
} TX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;


typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

typedef enum logic [5:0] {
	S_M1_IDLE,

	S_U_ADDRESS_UPDATE,
	S_DELAY_0,
	S_DELAY_1,
	S_FILL_0,
	S_FILL_1,
	S_FILL_2,
	S_FILL_3,
	S_FILL_4,
	S_FILL_5,
	S_COMMON_U_0,
	S_COMMON_U_1,
	S_COMMON_U_2,

	S_V_ADDRESS_UPDATE,
	S_DELAY_0_V,
	S_DELAY_1_V,
	S_FILL_0_V,
	S_FILL_1_V,
	S_FILL_2_V,
	S_FILL_3_V,
	S_FILL_4_V,
	S_FILL_5_V,
	S_COMMON_V_0,
	S_COMMON_V_1,
	S_COMMON_V_2,

	S_CONVERSION_Y,
	S_CONVERSION_U,
	S_CONVERSION_V,
	S_FILL_CONV_0,
	S_FILL_CONV_1,
	
	S_LEADOUT_1,
	S_LEADOUT_2,
	S_LEADOUT_3,
	S_LEADOUT_4,
	S_LEADOUT_5,
	S_LEADOUT_6,
	S_LEADOUT_7,
	S_LEADOUT_8,
	S_LEADOUT_9,
	S_LEADOUT_10,
	S_LEADOUT_11,
	S_LEADOUT_12
} M1_state_type;


typedef enum logic [5:0] { 
	S_M2_IDLE,
	S_SETUP_FETCH_Y,
	S_DELAY_M2_0,
	S_DELAY_M2_1,
	S_FETCH_S_Y0,
	S_DELAY_SETUP_CALC_T_0,
	S_DELAY_SETUP_CALC_T,
	S_C_TIMES_S_0,
	S_C_TIMES_S_1,
	S_C_TIMES_S_2,
	S_C_TIMES_S_3,
	S_C_TIMES_S_4,
	S_C_TIMES_S_5,
	S_C_TIMES_S_6,
	S_C_TIMES_S_7,
	S_C_TIMES_S_8,
	S_C_TIMES_S_9,
	S_C_TIMES_S_10,
	S_C_TIMES_S_11,
	S_C_TIMES_S_12,
	S_C_TIMES_S_13,
	S_C_TIMES_S_14,
	S_C_TIMES_S_15,
	S_C_TIMES_S_16,
	S_C_TIMES_S_17,
	S_SETUP_COMPUTE_S,
	S_DELAY_COMPUTE_S,
	S_S_TIMES_T_S0,
	S_S_TIMES_T_S1,
	S_S_TIMES_T_S2,
	S_S_TIMES_T_S3,
	S_S_TIMES_T_S4,
	S_S_TIMES_T_S5,
	S_S_TIMES_T_S6,
	S_S_TIMES_T_S7,
	S_S_TIMES_T_S8,
	S_S_TIMES_T_S9,
	S_S_TIMES_T_S10,
	S_S_TIMES_T_S11,
	S_S_TIMES_T_S12,
	S_S_TIMES_T_S13,
	S_S_TIMES_T_S14,
	S_S_TIMES_T_S15,
	S_S_TIMES_T_S16,
	S_S_TIMES_T_S17,
	S_SETUP_WRITE_S,
	S_DELAY_WRITE_S,
	S_WRITE_S
} M2_state_type;

`define DEFINE_STATE 1
`endif
